import type { Metadata } from 'next';
import { Grandiflora_One, Gayathri, Philosopher, Raleway, Raleway_Dots, Scope_One, Thasadith, Tsukimi_Rounded, Urbanist, Yomogi } from 'next/font/google'; 
import Navbar from '@/components/Navbar/Navbar';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const font = Urbanist({
  weight: ['100', '300', '400', '700'],
  subsets: ['latin'],
})


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={font.className} lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
